export const categories = {
    "Asistencia": ["asistencia", "reason", "analisisAusenciasRO", "invitados", "participacionOrgSup"],
    "Gestión": ["ptos", "implOrtcsOrgSup", "politicaDeCuadros", "sanciones",
        "planDeTrabajo", "reglamentosEstatutos"],
    "Acuerdos": ["totalDeAcuerdos",  "acuerdosSalidasExternas"],
    "Política": [
        "cp", "cp_agree",  "discusionDelitoCorrupcion"
    ],
    "Evaluación": [
        "rendicionMilitante",
        "rendicionDirigente",
        "analisisActFtal",
        "analisisObjs",
        "otrosAnalisisDisciplinarios",
        "evaluacion",
    ],
    "Organización": [
        "usoComisiones",
        "atencionFEU",
        "atencionUJC",
        "funcionamientoSindicato",
        "crecimiento",
        "desactivacion",
        "guardiaPCC",
        "trasladosIncorporacion",
    ],
};

export const indicators = [
    {
        key: "asistencia",
        category: "",
        name: "Asistencia",
        description: "Relación de asistencia",
    },
    {
        key: "reason",
        category: "",
        name: "Causas de ausencias",
        description: "Estado de Causas de Ausencias",
    },
    {
        key: "ptos",
        category: "",
        name: "Orden del Día",
        description: "Puntos del orden del día",
    },
    {
        category: "",
        key: "totalDeAcuerdos",
        name: "Total de Acuerdos",
        description: "Total de acuerdos tomados",
    },
    {
        category: "asistencia",
        key: "participacionOrgSup_Cte",
        name: "Participantes de la Org. Sup. del comité",
        description: "Participantes de la organización superior de comité",
    },
    {
        category: "",
        key: "participacionOrgSup_Mun",
        name: "Participantes de la Org. Sup. del Municipio",
        description: "Participantes de la organización superior del Municipio"
    },
    {
        category: "asistencia",
        key: "totalInvitados",
        name: "Invitados",
        description: "Invitados a la reunión",
    },
    {
        category: "",
        key: "reunionExtraordinaria",
        name: "Círculo Político",
        description: "Reunión de círculo de estudio",
    },
    {
        category: "",
        key: "cp_agree",
        name: "Acuerdos del Círculo Político",
        description: "Acuerdos dentro del círculo político",
    },
    {
        category: "",
        key: "redicionMilitantes",
        name: "Rendición Militante",
        description: "Rendición de cuentas de militantes",
    },
    {
        category: "",
        key: "redicionDirigAdm",
        name: "Rendición Dirigente",
        description: "Rendición de cuentas de dirigentes",
    },
    {
        category: "",
        key: "usoComisiones",
        name: "Uso de Comisiones",
        description: "Uso y funcionamiento de comisiones",
    },
    {
        category: "",
        key: "implOrtcsOrgSup",
        name: "Implementación ORTCS",
        description:
            "Implementación de estrategias ORTCS en la organización superior",
    },
    {
        category: "",
        key: "analisisActFtal",
        name: "Análisis de la Actividad Fundamental",
        description: "Análisis de actividades fundamentales",
    },
    {
        category: "",
        key: "discusionDelitoCorrupcionIlegalidad",
        name: "Discusión Delito Corrupción",
        description: "Discusión sobre delitos y corrupción",
    },
    {
        category: "",
        key: "analisisObjs",
        name: "Análisis de Objetivos",
        description: "Evaluación y análisis de objetivos estratégicos",
    },
    {
        category: "",
        key: "politicaDeCuadros",
        name: "Política de Cuadros",
        description: "Políticas de cuadros y liderazgo",
    },
    {
        category: "",
        key: "atencionFEU",
        name: "Atención FEU",
        description: "Atención a la Federación Estudiantil Universitaria",
    },
    {
        category: "",
        key: "atencionUJC",
        name: "Atención UJC",
        description: "Atención a la Unión de Jóvenes Comunistas",
    },
    {
        category: "",
        key: "funcionamientoSindicato",
        name: "Funcionamiento del Sindicato",
        description: "Evaluación del funcionamiento sindical",
    },
    {
        category: "",
        key: "reglamentosEstatutos",
        name: "Reglamentos y Estatutos",
        description: "Revisión y aplicación de reglamentos y estatutos",
    },
    {
        category: "asistencia",
        key: "analisisAusenciasRO",
        name: "Análisis de Ausencias RO",
        description: "Evaluación de ausencias en reuniones oficiales",
    },
    {
        category: "",
        key: "otrosAnalisisDisciplinarios",
        name: "Otros Análisis Disciplinarios",
        description: "Evaluación de otros aspectos disciplinarios",
    },
    {
        category: "",
        key: "planDeTrabajo",
        name: "Plan de Trabajo",
        description: "Planificación y seguimiento de tareas",
    },
    {
        category: "",
        key: "sanciones",
        name: "Sanciones",
        description: "Registro y control de sanciones",
    },
    {
        category: "",
        key: "crecimiento",
        name: "Crecimiento",
        description: "Indicadores de crecimiento organizacional",
    },
    {
        category: "",
        key: "desactivacion",
        name: "Desactivaciones",
        description: "Registro de miembros desactivados",
    },
    {
        category: "",
        key: "evaluacion",
        name: "Evaluación",
        description: "Evaluación general del desempeño",
    },
    {
        category: "",
        key: "guardiaPCC",
        name: "Guardia PCC",
        description: "Guardias programadas en el PCC",
    },
    {
        category: "",
        key: "acuerdosSalidasExternas",   
        name: "Acuerdos de Salidas Externas",
        description: "Acuerdos relacionados con salidas externas",
    },
    {
        category: "",
        key: "trasladosIncorporacion",
        name: "Traslados e Incorporaciones",
        description: "Registro de traslados e incorporaciones",
    },
];