export class Indicadores{
    'Puntos Orden Día'
    'Total de acuerdos'
    'Particip. Org. Sup'
    'Invitados'
    'Rendición'
    'Uso Comis'
    'Impl. ortcs Org Sup'
    'Análisis Act Ftal'
    'Discus. Delito, corrup'
    'Análisis objs'
    'Polít de cuadros'
    'Atención FEU'
    'Atención UJC'
    'Functo Sind'
    'Reglam, Estatutos'
    'Análisis Aus. R/O'
    'Otros Análisis Discp'
    'Plan de Trab'
    'Sanciones'
    'Crecimiento'
    'Desactivación'
    'Evaluación'
    'Guardia PCC'
    'acuerdos salidas ext'
    'Traslados e incorporaciones'
    'Círculo Político'
    'acuerdos CPolítico'
}